### ISSUE TITLE
[Epic] Als gebruiker wil ik een overzichtelijke groepspagina, zodat ik gemakkelijk een nieuwe groep kan maken en kan beginnen met swipen naar films of series

### ISSUE THREAD

**Issue by DDuijker** [DDuijker/Swiping-App#111]
### Acceptance criteria

- [x] De hoofdpagina moet een duidelijke titel en navigatie-elementen bevatten voor gebruiksvriendelijkheid.
- [ ] Er moet een knop zijn met de tekst "Nieuwe Groep Maken" of een '+'-teken, die de gebruiker naar een pagina leidt om een nieuwe groep aan te maken.
- [ ] Wanneer de gebruiker op "Nieuwe Groep Maken" klikt, moet er een pop-up of nieuwe pagina verschijnen waarin de gebruiker de naam van de groep en eventuele aanvullende instellingen kan invoeren.
- [ ] Na het aanmaken van een groep moet de gebruiker een optie hebben om doorgestuurd te worden naar de swipe-interface, waar ze kunnen beginnen met het selecteren van films of series.
- [ ] De hoofdpagina moet een lijst van bestaande groepen weergeven, met de mogelijkheid om een groep te selecteren en direct naar de swipe-interface te gaan.
- [ ] Gebruikers moeten een melding ontvangen als ze succesvol een groep hebben aangemaakt of als er een fout optreedt tijdens het proces.
